// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto
// Protobuf Java Version: 4.28.1

package io.grpc.health.v1;

public final class HealthProto {
  private HealthProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      HealthProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthCheckResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033grpc/health/v1/health.proto\022\016grpc.heal" +
      "th.v1\"%\n\022HealthCheckRequest\022\017\n\007service\030\001" +
      " \001(\t\"\224\001\n\023HealthCheckResponse\022A\n\006status\030\001" +
      " \001(\01621.grpc.health.v1.HealthCheckRespons" +
      "e.ServingStatus\":\n\rServingStatus\022\013\n\007UNKN" +
      "OWN\020\000\022\013\n\007SERVING\020\001\022\017\n\013NOT_SERVING\020\0022Z\n\006H" +
      "ealth\022P\n\005Check\022\".grpc.health.v1.HealthCh" +
      "eckRequest\032#.grpc.health.v1.HealthCheckR" +
      "esponseBa\n\021io.grpc.health.v1B\013HealthProt" +
      "oP\001Z,google.golang.org/grpc/health/grpc_" +
      "health_v1\252\002\016Grpc.Health.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_health_v1_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_health_v1_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthCheckRequest_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_grpc_health_v1_HealthCheckResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_health_v1_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
