# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: currency.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import demo_pb2 as demo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63urrency.proto\x12\x0bhipstershop\x1a\ndemo.proto\"8\n\x1eGetSupportedCurrenciesResponse\x12\x16\n\x0e\x63urrency_codes\x18\x01 \x03(\t\"N\n\x19\x43urrencyConversionRequest\x12 \n\x04\x66rom\x18\x01 \x01(\x0b\x32\x12.hipstershop.Money\x12\x0f\n\x07to_code\x18\x02 \x01(\t2\xb7\x01\n\x0f\x43urrencyService\x12[\n\x16GetSupportedCurrencies\x12\x12.hipstershop.Empty\x1a+.hipstershop.GetSupportedCurrenciesResponse\"\x00\x12G\n\x07\x43onvert\x12&.hipstershop.CurrencyConversionRequest\x1a\x12.hipstershop.Money\"\x00\x42\x41Z?github.com/Ayanamiz41/microservice-demo/genproto/go/hipstershopb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z?github.com/Ayanamiz41/microservice-demo/genproto/go/hipstershop'
  _globals['_GETSUPPORTEDCURRENCIESRESPONSE']._serialized_start=43
  _globals['_GETSUPPORTEDCURRENCIESRESPONSE']._serialized_end=99
  _globals['_CURRENCYCONVERSIONREQUEST']._serialized_start=101
  _globals['_CURRENCYCONVERSIONREQUEST']._serialized_end=179
  _globals['_CURRENCYSERVICE']._serialized_start=182
  _globals['_CURRENCYSERVICE']._serialized_end=365
# @@protoc_insertion_point(module_scope)
