// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: recommendation.proto
// Protobuf Java Version: 4.28.1

package hipstershop;

public final class Recommendation {
  private Recommendation() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 1,
      /* suffix= */ "",
      Recommendation.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ListRecommendationsRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hipstershop.ListRecommendationsRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    java.lang.String getUserId();
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>repeated string product_ids = 2;</code>
     * @return A list containing the productIds.
     */
    java.util.List<java.lang.String>
        getProductIdsList();
    /**
     * <code>repeated string product_ids = 2;</code>
     * @return The count of productIds.
     */
    int getProductIdsCount();
    /**
     * <code>repeated string product_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    java.lang.String getProductIds(int index);
    /**
     * <code>repeated string product_ids = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productIds at the given index.
     */
    com.google.protobuf.ByteString
        getProductIdsBytes(int index);
  }
  /**
   * Protobuf type {@code hipstershop.ListRecommendationsRequest}
   */
  public static final class ListRecommendationsRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hipstershop.ListRecommendationsRequest)
      ListRecommendationsRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        ListRecommendationsRequest.class.getName());
    }
    // Use ListRecommendationsRequest.newBuilder() to construct.
    private ListRecommendationsRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ListRecommendationsRequest() {
      userId_ = "";
      productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hipstershop.Recommendation.ListRecommendationsRequest.class, hipstershop.Recommendation.ListRecommendationsRequest.Builder.class);
    }

    public static final int USER_ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userId_ = "";
    /**
     * <code>string user_id = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id = 1;</code>
     * @return The bytes for userId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_IDS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList productIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string product_ids = 2;</code>
     * @return A list containing the productIds.
     */
    public com.google.protobuf.ProtocolStringList
        getProductIdsList() {
      return productIds_;
    }
    /**
     * <code>repeated string product_ids = 2;</code>
     * @return The count of productIds.
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated string product_ids = 2;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    public java.lang.String getProductIds(int index) {
      return productIds_.get(index);
    }
    /**
     * <code>repeated string product_ids = 2;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productIds at the given index.
     */
    public com.google.protobuf.ByteString
        getProductIdsBytes(int index) {
      return productIds_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_);
      }
      for (int i = 0; i < productIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, productIds_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(userId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < productIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(productIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProductIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof hipstershop.Recommendation.ListRecommendationsRequest)) {
        return super.equals(obj);
      }
      hipstershop.Recommendation.ListRecommendationsRequest other = (hipstershop.Recommendation.ListRecommendationsRequest) obj;

      if (!getUserId()
          .equals(other.getUserId())) return false;
      if (!getProductIdsList()
          .equals(other.getProductIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserId().hashCode();
      if (getProductIdsCount() > 0) {
        hash = (37 * hash) + PRODUCT_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getProductIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static hipstershop.Recommendation.ListRecommendationsRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static hipstershop.Recommendation.ListRecommendationsRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static hipstershop.Recommendation.ListRecommendationsRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hipstershop.Recommendation.ListRecommendationsRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hipstershop.ListRecommendationsRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hipstershop.ListRecommendationsRequest)
        hipstershop.Recommendation.ListRecommendationsRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hipstershop.Recommendation.ListRecommendationsRequest.class, hipstershop.Recommendation.ListRecommendationsRequest.Builder.class);
      }

      // Construct using hipstershop.Recommendation.ListRecommendationsRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        userId_ = "";
        productIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsRequest_descriptor;
      }

      @java.lang.Override
      public hipstershop.Recommendation.ListRecommendationsRequest getDefaultInstanceForType() {
        return hipstershop.Recommendation.ListRecommendationsRequest.getDefaultInstance();
      }

      @java.lang.Override
      public hipstershop.Recommendation.ListRecommendationsRequest build() {
        hipstershop.Recommendation.ListRecommendationsRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public hipstershop.Recommendation.ListRecommendationsRequest buildPartial() {
        hipstershop.Recommendation.ListRecommendationsRequest result = new hipstershop.Recommendation.ListRecommendationsRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(hipstershop.Recommendation.ListRecommendationsRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.userId_ = userId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          productIds_.makeImmutable();
          result.productIds_ = productIds_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hipstershop.Recommendation.ListRecommendationsRequest) {
          return mergeFrom((hipstershop.Recommendation.ListRecommendationsRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hipstershop.Recommendation.ListRecommendationsRequest other) {
        if (other == hipstershop.Recommendation.ListRecommendationsRequest.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.productIds_.isEmpty()) {
          if (productIds_.isEmpty()) {
            productIds_ = other.productIds_;
            bitField0_ |= 0x00000002;
          } else {
            ensureProductIdsIsMutable();
            productIds_.addAll(other.productIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                userId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureProductIdsIsMutable();
                productIds_.add(s);
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object userId_ = "";
      /**
       * <code>string user_id = 1;</code>
       * @return The userId.
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id = 1;</code>
       * @return The bytes for userId.
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        userId_ = getDefaultInstance().getUserId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string user_id = 1;</code>
       * @param value The bytes for userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureProductIdsIsMutable() {
        if (!productIds_.isModifiable()) {
          productIds_ = new com.google.protobuf.LazyStringArrayList(productIds_);
        }
        bitField0_ |= 0x00000002;
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @return A list containing the productIds.
       */
      public com.google.protobuf.ProtocolStringList
          getProductIdsList() {
        productIds_.makeImmutable();
        return productIds_;
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @return The count of productIds.
       */
      public int getProductIdsCount() {
        return productIds_.size();
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @param index The index of the element to return.
       * @return The productIds at the given index.
       */
      public java.lang.String getProductIds(int index) {
        return productIds_.get(index);
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @param index The index of the value to return.
       * @return The bytes of the productIds at the given index.
       */
      public com.google.protobuf.ByteString
          getProductIdsBytes(int index) {
        return productIds_.getByteString(index);
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @param index The index to set the value at.
       * @param value The productIds to set.
       * @return This builder for chaining.
       */
      public Builder setProductIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProductIdsIsMutable();
        productIds_.set(index, value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @param value The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProductIdsIsMutable();
        productIds_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @param values The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllProductIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureProductIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productIds_);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductIds() {
        productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string product_ids = 2;</code>
       * @param value The bytes of the productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureProductIdsIsMutable();
        productIds_.add(value);
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hipstershop.ListRecommendationsRequest)
    }

    // @@protoc_insertion_point(class_scope:hipstershop.ListRecommendationsRequest)
    private static final hipstershop.Recommendation.ListRecommendationsRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hipstershop.Recommendation.ListRecommendationsRequest();
    }

    public static hipstershop.Recommendation.ListRecommendationsRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListRecommendationsRequest>
        PARSER = new com.google.protobuf.AbstractParser<ListRecommendationsRequest>() {
      @java.lang.Override
      public ListRecommendationsRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ListRecommendationsRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListRecommendationsRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public hipstershop.Recommendation.ListRecommendationsRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ListRecommendationsResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hipstershop.ListRecommendationsResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string product_ids = 1;</code>
     * @return A list containing the productIds.
     */
    java.util.List<java.lang.String>
        getProductIdsList();
    /**
     * <code>repeated string product_ids = 1;</code>
     * @return The count of productIds.
     */
    int getProductIdsCount();
    /**
     * <code>repeated string product_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    java.lang.String getProductIds(int index);
    /**
     * <code>repeated string product_ids = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productIds at the given index.
     */
    com.google.protobuf.ByteString
        getProductIdsBytes(int index);
  }
  /**
   * Protobuf type {@code hipstershop.ListRecommendationsResponse}
   */
  public static final class ListRecommendationsResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hipstershop.ListRecommendationsResponse)
      ListRecommendationsResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 1,
        /* suffix= */ "",
        ListRecommendationsResponse.class.getName());
    }
    // Use ListRecommendationsResponse.newBuilder() to construct.
    private ListRecommendationsResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ListRecommendationsResponse() {
      productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hipstershop.Recommendation.ListRecommendationsResponse.class, hipstershop.Recommendation.ListRecommendationsResponse.Builder.class);
    }

    public static final int PRODUCT_IDS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList productIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string product_ids = 1;</code>
     * @return A list containing the productIds.
     */
    public com.google.protobuf.ProtocolStringList
        getProductIdsList() {
      return productIds_;
    }
    /**
     * <code>repeated string product_ids = 1;</code>
     * @return The count of productIds.
     */
    public int getProductIdsCount() {
      return productIds_.size();
    }
    /**
     * <code>repeated string product_ids = 1;</code>
     * @param index The index of the element to return.
     * @return The productIds at the given index.
     */
    public java.lang.String getProductIds(int index) {
      return productIds_.get(index);
    }
    /**
     * <code>repeated string product_ids = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the productIds at the given index.
     */
    public com.google.protobuf.ByteString
        getProductIdsBytes(int index) {
      return productIds_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < productIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, productIds_.getRaw(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < productIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(productIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getProductIdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof hipstershop.Recommendation.ListRecommendationsResponse)) {
        return super.equals(obj);
      }
      hipstershop.Recommendation.ListRecommendationsResponse other = (hipstershop.Recommendation.ListRecommendationsResponse) obj;

      if (!getProductIdsList()
          .equals(other.getProductIdsList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getProductIdsCount() > 0) {
        hash = (37 * hash) + PRODUCT_IDS_FIELD_NUMBER;
        hash = (53 * hash) + getProductIdsList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static hipstershop.Recommendation.ListRecommendationsResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static hipstershop.Recommendation.ListRecommendationsResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static hipstershop.Recommendation.ListRecommendationsResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hipstershop.Recommendation.ListRecommendationsResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hipstershop.ListRecommendationsResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hipstershop.ListRecommendationsResponse)
        hipstershop.Recommendation.ListRecommendationsResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hipstershop.Recommendation.ListRecommendationsResponse.class, hipstershop.Recommendation.ListRecommendationsResponse.Builder.class);
      }

      // Construct using hipstershop.Recommendation.ListRecommendationsResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        productIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hipstershop.Recommendation.internal_static_hipstershop_ListRecommendationsResponse_descriptor;
      }

      @java.lang.Override
      public hipstershop.Recommendation.ListRecommendationsResponse getDefaultInstanceForType() {
        return hipstershop.Recommendation.ListRecommendationsResponse.getDefaultInstance();
      }

      @java.lang.Override
      public hipstershop.Recommendation.ListRecommendationsResponse build() {
        hipstershop.Recommendation.ListRecommendationsResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public hipstershop.Recommendation.ListRecommendationsResponse buildPartial() {
        hipstershop.Recommendation.ListRecommendationsResponse result = new hipstershop.Recommendation.ListRecommendationsResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(hipstershop.Recommendation.ListRecommendationsResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          productIds_.makeImmutable();
          result.productIds_ = productIds_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hipstershop.Recommendation.ListRecommendationsResponse) {
          return mergeFrom((hipstershop.Recommendation.ListRecommendationsResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hipstershop.Recommendation.ListRecommendationsResponse other) {
        if (other == hipstershop.Recommendation.ListRecommendationsResponse.getDefaultInstance()) return this;
        if (!other.productIds_.isEmpty()) {
          if (productIds_.isEmpty()) {
            productIds_ = other.productIds_;
            bitField0_ |= 0x00000001;
          } else {
            ensureProductIdsIsMutable();
            productIds_.addAll(other.productIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureProductIdsIsMutable();
                productIds_.add(s);
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureProductIdsIsMutable() {
        if (!productIds_.isModifiable()) {
          productIds_ = new com.google.protobuf.LazyStringArrayList(productIds_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @return A list containing the productIds.
       */
      public com.google.protobuf.ProtocolStringList
          getProductIdsList() {
        productIds_.makeImmutable();
        return productIds_;
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @return The count of productIds.
       */
      public int getProductIdsCount() {
        return productIds_.size();
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @param index The index of the element to return.
       * @return The productIds at the given index.
       */
      public java.lang.String getProductIds(int index) {
        return productIds_.get(index);
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the productIds at the given index.
       */
      public com.google.protobuf.ByteString
          getProductIdsBytes(int index) {
        return productIds_.getByteString(index);
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @param index The index to set the value at.
       * @param value The productIds to set.
       * @return This builder for chaining.
       */
      public Builder setProductIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProductIdsIsMutable();
        productIds_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @param value The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureProductIdsIsMutable();
        productIds_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @param values The productIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllProductIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureProductIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, productIds_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductIds() {
        productIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string product_ids = 1;</code>
       * @param value The bytes of the productIds to add.
       * @return This builder for chaining.
       */
      public Builder addProductIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureProductIdsIsMutable();
        productIds_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:hipstershop.ListRecommendationsResponse)
    }

    // @@protoc_insertion_point(class_scope:hipstershop.ListRecommendationsResponse)
    private static final hipstershop.Recommendation.ListRecommendationsResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hipstershop.Recommendation.ListRecommendationsResponse();
    }

    public static hipstershop.Recommendation.ListRecommendationsResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ListRecommendationsResponse>
        PARSER = new com.google.protobuf.AbstractParser<ListRecommendationsResponse>() {
      @java.lang.Override
      public ListRecommendationsResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ListRecommendationsResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ListRecommendationsResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public hipstershop.Recommendation.ListRecommendationsResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hipstershop_ListRecommendationsRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hipstershop_ListRecommendationsRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hipstershop_ListRecommendationsResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hipstershop_ListRecommendationsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024recommendation.proto\022\013hipstershop\"B\n\032L" +
      "istRecommendationsRequest\022\017\n\007user_id\030\001 \001" +
      "(\t\022\023\n\013product_ids\030\002 \003(\t\"2\n\033ListRecommend" +
      "ationsResponse\022\023\n\013product_ids\030\001 \003(\t2\203\001\n\025" +
      "RecommendationService\022j\n\023ListRecommendat" +
      "ions\022\'.hipstershop.ListRecommendationsRe" +
      "quest\032(.hipstershop.ListRecommendationsR" +
      "esponse\"\000BAZ?github.com/Ayanamiz41/micro" +
      "service-demo/genproto/go/hipstershopb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_hipstershop_ListRecommendationsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hipstershop_ListRecommendationsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hipstershop_ListRecommendationsRequest_descriptor,
        new java.lang.String[] { "UserId", "ProductIds", });
    internal_static_hipstershop_ListRecommendationsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hipstershop_ListRecommendationsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hipstershop_ListRecommendationsResponse_descriptor,
        new java.lang.String[] { "ProductIds", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
