// shopping_assistant.proto — ShoppingAssistantService contract (Python
// shoppingassistantservice).
//
// NOTE: upstream GoogleCloudPlatform/microservices-demo implements this
// service as a cloud-only Flask app backed by AlloyDB/Gemini and defines no
// gRPC contract. This replica replaces it with a simple local gRPC assistant
// (rule/catalog based); the contract below is the simplified in-repo
// definition for that scope.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.1
// source: shopping_assistant.proto

package hipstershop

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShoppingAssistantRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	UserId string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The user's message / question.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Opaque conversation id; empty on the first message of a conversation.
	ConversationId string `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	// Optional catalog context (e.g. product ids currently on screen).
	ContextProductIds []string `protobuf:"bytes,4,rep,name=context_product_ids,json=contextProductIds,proto3" json:"context_product_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ShoppingAssistantRequest) Reset() {
	*x = ShoppingAssistantRequest{}
	mi := &file_shopping_assistant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingAssistantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingAssistantRequest) ProtoMessage() {}

func (x *ShoppingAssistantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_assistant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingAssistantRequest.ProtoReflect.Descriptor instead.
func (*ShoppingAssistantRequest) Descriptor() ([]byte, []int) {
	return file_shopping_assistant_proto_rawDescGZIP(), []int{0}
}

func (x *ShoppingAssistantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShoppingAssistantRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShoppingAssistantRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ShoppingAssistantRequest) GetContextProductIds() []string {
	if x != nil {
		return x.ContextProductIds
	}
	return nil
}

type ShoppingAssistantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The assistant's textual reply.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Echoes/allocates the conversation id for follow-up messages.
	ConversationId string `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShoppingAssistantResponse) Reset() {
	*x = ShoppingAssistantResponse{}
	mi := &file_shopping_assistant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShoppingAssistantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShoppingAssistantResponse) ProtoMessage() {}

func (x *ShoppingAssistantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shopping_assistant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShoppingAssistantResponse.ProtoReflect.Descriptor instead.
func (*ShoppingAssistantResponse) Descriptor() ([]byte, []int) {
	return file_shopping_assistant_proto_rawDescGZIP(), []int{1}
}

func (x *ShoppingAssistantResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ShoppingAssistantResponse) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

var File_shopping_assistant_proto protoreflect.FileDescriptor

const file_shopping_assistant_proto_rawDesc = "" +
	"\n" +
	"\x18shopping_assistant.proto\x12\vhipstershop\"\xa6\x01\n" +
	"\x18ShoppingAssistantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12.\n" +
	"\x13context_product_ids\x18\x04 \x03(\tR\x11contextProductIds\"^\n" +
	"\x19ShoppingAssistantResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId2|\n" +
	"\x18ShoppingAssistantService\x12`\n" +
	"\rGetCompletion\x12%.hipstershop.ShoppingAssistantRequest\x1a&.hipstershop.ShoppingAssistantResponse\"\x00BAZ?github.com/Ayanamiz41/microservice-demo/genproto/go/hipstershopb\x06proto3"

var (
	file_shopping_assistant_proto_rawDescOnce sync.Once
	file_shopping_assistant_proto_rawDescData []byte
)

func file_shopping_assistant_proto_rawDescGZIP() []byte {
	file_shopping_assistant_proto_rawDescOnce.Do(func() {
		file_shopping_assistant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shopping_assistant_proto_rawDesc), len(file_shopping_assistant_proto_rawDesc)))
	})
	return file_shopping_assistant_proto_rawDescData
}

var file_shopping_assistant_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_shopping_assistant_proto_goTypes = []any{
	(*ShoppingAssistantRequest)(nil),  // 0: hipstershop.ShoppingAssistantRequest
	(*ShoppingAssistantResponse)(nil), // 1: hipstershop.ShoppingAssistantResponse
}
var file_shopping_assistant_proto_depIdxs = []int32{
	0, // 0: hipstershop.ShoppingAssistantService.GetCompletion:input_type -> hipstershop.ShoppingAssistantRequest
	1, // 1: hipstershop.ShoppingAssistantService.GetCompletion:output_type -> hipstershop.ShoppingAssistantResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shopping_assistant_proto_init() }
func file_shopping_assistant_proto_init() {
	if File_shopping_assistant_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shopping_assistant_proto_rawDesc), len(file_shopping_assistant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shopping_assistant_proto_goTypes,
		DependencyIndexes: file_shopping_assistant_proto_depIdxs,
		MessageInfos:      file_shopping_assistant_proto_msgTypes,
	}.Build()
	File_shopping_assistant_proto = out.File
	file_shopping_assistant_proto_goTypes = nil
	file_shopping_assistant_proto_depIdxs = nil
}
